"""Launch the multi-LiDAR calibrator node.

The parameter file supplies all runtime config including `output_dir`. No
launch-arg default is provided for parameter_file — callers must pass one,
typically generated by `calibrate_live` from a preset.
"""
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    params_declare = DeclareLaunchArgument(
        "parameter_file",
        description="Absolute path to the ROS 2 parameters YAML.",
    )

    return LaunchDescription([
        params_declare,
        Node(
            package="multi_lidar_calibrator",
            executable="multi_lidar_calibrator",
            name="multi_lidar_calibration_node",
            parameters=[LaunchConfiguration("parameter_file")],
            output="screen",
        ),
    ])
